model = "flux_2_klein_9b_q6p.ckpt"

negative_prompt = "錯誤的肢體, 多餘的肢體, 超過兩隻手, 超過兩隻腳, 肢體畸形, 過度曝光, 普通臉, 平均臉, 典型AI臉, 千篇一律的臉, 相同五官, 雷同特徵, 通用臉型"

width = 1280
height = 1280
steps = 4
cfg = 1.0
strength = 1.0

[config]
sampler = 16
seedMode = 2
shift = 3.0
resolutionDependentShift = false
clipSkip = 2
sharpness = 0.0
maskBlur = 2.5
maskBlurOutset = 0
preserveOriginalAfterInpaint = true
colorCalibration = "none"
hiresFix = false
tiledDecoding = false
tiledDiffusion = false
batchSize = 1
batchCount = 1
upscaler = ""
refinerModel = ""
faceRestoration = ""
loras = []
controls = []
